name: Parse network data and publish *.json files

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron:  '0 */6 * * *'    # Every 6 hours
  workflow_dispatch:
permissions:
  actions: write-all
jobs:
  generate-znn-node-info:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; 
            then pip install -r ./requirements.txt; 
        fi
    - name: Produce Release files
      run: python main.py
    - name: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@2.9.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: data/*.json
        tag: public_nodes
        file_glob: true
        overwrite: true
        body: ""
    - uses: gautamkrishnar/keepalive-workflow@v2 
